<?php
/**
 * @file
 * glacier_content_blocks_section.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function glacier_content_blocks_section_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Grid container',
    'description' => NULL,
    'format' => 'full_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '17c0c7a1-b673-45fa-859d-7ceb21e94565',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Grid container',
          'format' => NULL,
          'safe_value' => 'Grid container',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'full_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'o-grid',
          'format' => NULL,
          'safe_value' => 'o-grid',
        ),
        1 => array(
          'value' => 'o-grid--spaced',
          'format' => NULL,
          'safe_value' => 'o-grid--spaced',
        ),
      ),
    ),
    'name_original' => 'Grid container',
    'entity_translation_handler_id' => 'taxonomy_term-eid-8-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 8,
          'revision_id' => 8,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1442587810,
          'changed' => 1442587810,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Grid item (4/12)',
    'description' => NULL,
    'format' => 'full_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '60b84225-2264-43a1-8238-bc0ae36bc0a1',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Grid item (4/12)',
          'format' => NULL,
          'safe_value' => 'Grid item (4/12)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'full_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'o-grid__item',
          'format' => NULL,
          'safe_value' => 'o-grid__item',
        ),
        1 => array(
          'value' => 'u-width--12',
          'format' => NULL,
          'safe_value' => 'u-width--12',
        ),
        2 => array(
          'value' => 'u-width--m--4',
          'format' => NULL,
          'safe_value' => 'u-width--m--4',
        ),
      ),
    ),
    'name_original' => 'Grid item (4/12)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-11-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 11,
          'revision_id' => 11,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1442587933,
          'changed' => 1442587933,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Grid item (3/12)',
    'description' => NULL,
    'format' => 'full_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => '9e850018-9dc1-404d-a963-c5e34ddb53ac',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Grid item (3/12)',
          'format' => NULL,
          'safe_value' => 'Grid item (3/12)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'full_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'o-grid__item',
          'format' => NULL,
          'safe_value' => 'o-grid__item',
        ),
        1 => array(
          'value' => 'u-width--12',
          'format' => NULL,
          'safe_value' => 'u-width--12',
        ),
        2 => array(
          'value' => 'u-width--m--3',
          'format' => NULL,
          'safe_value' => 'u-width--m--3',
        ),
      ),
    ),
    'name_original' => 'Grid item (3/12)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-12-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 12,
          'revision_id' => 12,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1442587963,
          'changed' => 1442587963,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Grid item (8/12)',
    'description' => NULL,
    'format' => 'full_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => 'c98cc018-aef7-4655-9dc4-fc44252706c6',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Grid item (8/12)',
          'format' => NULL,
          'safe_value' => 'Grid item (8/12)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'full_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'o-grid__item',
          'format' => NULL,
          'safe_value' => 'o-grid__item',
        ),
        1 => array(
          'value' => 'u-width--12',
          'format' => NULL,
          'safe_value' => 'u-width--12',
        ),
        2 => array(
          'value' => 'u-width--m--8',
          'format' => NULL,
          'safe_value' => 'u-width--m--8',
        ),
      ),
    ),
    'name_original' => 'Grid item (8/12)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-10-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 10,
          'revision_id' => 10,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1442587897,
          'changed' => 1442587897,
        ),
      ),
    ),
    'description_original' => '',
  );
  $terms[] = array(
    'name' => 'Grid item (6/12)',
    'description' => NULL,
    'format' => 'full_html',
    'weight' => 0,
    'rh_action' => NULL,
    'rh_redirect' => NULL,
    'rh_redirect_response' => NULL,
    'uuid' => 'fad51215-c687-4f9e-bf49-60c8de4822d3',
    'vocabulary_machine_name' => 'content_block_styles',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Grid item (6/12)',
          'format' => NULL,
          'safe_value' => 'Grid item (6/12)',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'full_html',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_content_block_classes' => array(
      'und' => array(
        0 => array(
          'value' => 'o-grid__item',
          'format' => NULL,
          'safe_value' => 'o-grid__item',
        ),
        1 => array(
          'value' => 'u-width--12',
          'format' => NULL,
          'safe_value' => 'u-width--12',
        ),
        2 => array(
          'value' => 'u-width--m--6',
          'format' => NULL,
          'safe_value' => 'u-width--m--6',
        ),
      ),
    ),
    'name_original' => 'Grid item (6/12)',
    'entity_translation_handler_id' => 'taxonomy_term-eid-9-0',
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 9,
          'revision_id' => 9,
          'language' => 'en',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1442587860,
          'changed' => 1442587860,
        ),
      ),
    ),
    'description_original' => '',
  );
  return $terms;
}
